'use strict';
const reduced = matchMedia('(prefers-reduced-motion: reduce)');
const sources=[
['sputnik','Первый спутник','NASA · Dawn of the Space Age','https://www.nasa.gov/history/dawn-of-the-space-age/'],
['gagarin','Первый человек на орбите','NASA · April 1961 — First Human Entered Space','https://www.nasa.gov/image-article/april-1961-first-human-entered-space/'],
['tereshkova','Полёт Валентины Терешковой','NASA · Sally Ride and Valentina Tereshkova','https://www.nasa.gov/history/sally-ride-and-valentina-tereshkova-changing-the-course-of-human-space-exploration/'],
['leonov','Первый выход в открытый космос','NASA · Spacewalking History','https://www.nasa.gov/history/space-station-20th-spacewalking-history/'],
['luna','Автоматические лунные миссии','NASA Science · Moon Missions','https://science.nasa.gov/moon/missions/'],
['soil','Возвращение лунного грунта','NASA / LRO · Luna 16','https://science.nasa.gov/photojournal/luna-16/'],
['venera','Программа «Венера»','NASA Science · Venus Exploration','https://science.nasa.gov/venus/exploration/'],
['venusfacts','Условия на Венере','NASA Science · Venus Facts','https://science.nasa.gov/venus/venus-facts/'],
['venusphoto','Снимок поверхности «Венеры-13»','NASA / APOD · A Venus Landing (оригинал по ссылке)','https://science.nasa.gov/image-article/apod-1999-january-24-a-venus-landing/'],
['mars','«Марс-3»: посадка и потеря сигнала','NASA GISS · Mars Landers','https://www.giss.nasa.gov/tools/mars24/help/landers.html'],
['salyut','«Салют-1» и «Союз-11»','NASA · Launch of the World’s First Space Station','https://www.nasa.gov/missions/station/50-years-ago-launch-of-salyut-the-worlds-first-space-station/'],
['mir','Развитие модульной станции «Мир»','NASA · Launch of Mir Space Station’s First Module','https://www.nasa.gov/history/35-years-ago-launch-of-mir-space-stations-first-module/'],
['hardware','Технологии «Союза», «Салюта» и «Мира»','NASA · Mir Hardware Heritage, 1995 (PDF)','https://sma.nasa.gov/SignificantIncidents/assets/mir-hardware-heritage.pdf'],
['n1','Пилотируемая лунная программа и Н-1','Б. Е. Черток · Rockets and People, том IV, издание NASA (PDF)','https://www.nasa.gov/wp-content/uploads/2015/04/621513main_rocketspeoplevolume4-ebook.pdf'],
['komarov','Гибель Владимира Комарова','NASA NTRS · Перевод сообщения ТАСС, 1967','https://ntrs.nasa.gov/citations/19670017082'],
['astp','От соперничества к сотрудничеству','NASA · 45 Years Ago: Soyuz and Apollo Launch','https://www.nasa.gov/history/45-years-ago-soyuz-and-apollo-launch/'],
['chronicle','Даты посадок и результаты межпланетных миссий','NASA · Deep Space Chronicle, 2002 (PDF)','https://science.nasa.gov/wp-content/uploads/2023/09/DSC_monograph24.pdf']
];
const ref=(id,label='Источник и материалы')=>`<a class="source-ref" href="#source-${id}">${label} ↗</a>`;
const eyebrow=(n,t)=>`<div class="eyebrow">${n} / ${t}</div>`;
const detail=(text)=>`<details><summary>Подробнее о миссии</summary><p>${text}</p></details>`;
const moonMissions=[['1959','«Луна-2»','14 сентября 1959 · достижение поверхности','Первый аппарат, достигший поверхности Луны. Это было столкновение, а не мягкая посадка. Дата приведена по московскому времени; по UTC — 13 сентября.'],['1959','«Луна-3»','7 октября 1959 · обратная сторона','Первые фотографии обратной стороны Луны. Автоматическая станция сделала видимым полушарие, которое нельзя увидеть с Земли.'],['1966','«Луна-9»','3 февраля 1966 · мягкая посадка','Первая успешная мягкая посадка на Луну и передача панорам с её поверхности. Аппарат продолжил работать после прилунения.'],['1970','«Луна-16»','24 сентября 1970 · возвращение','Первая автоматическая доставка лунного грунта на Землю: около 101 грамма. Образцы позволили исследовать вещество Луны в лабораториях.'],['1970','«Луноход-1»','17 ноября 1970 · подвижная лаборатория','«Луна-17» доставила первый успешно работавший планетоход на другое небесное тело. Управляемый с Земли аппарат исследовал поверхность Луны.']];
const venusMissions=[['1970','«Венера-7»','15 декабря 1970','Первая успешная мягкая посадка на другую планету с передачей данных с поверхности. Измерения подтвердили чрезвычайно высокую температуру.'],['1975','«Венера-9»','22 октября 1975','Первые фотографии, переданные с поверхности другой планеты. Орбитальный аппарат служил ретранслятором для посадочного модуля.'],['1982','«Венера-13»','1 марта 1982','Цветные панорамы поверхности и анализ состава грунта. Автоматические приборы работали в условиях, несовместимых с жизнью человека.']];
const humanData=[['gagarin','12.04.1961','Юрий<br>Гагарин','«ВОСТОК-1» / ОДИН ОБОРОТ ВОКРУГ ЗЕМЛИ','Человек впервые увидел Землю с орбиты. Полёт Гагарина показал, что человек может перенести запуск, невесомость и возвращение.','108 минут — общепринятая продолжительность полёта. Перед приземлением Гагарин катапультировался из спускаемого аппарата и опустился на собственном парашюте.','1961'],['tereshkova','16.06.1963','Валентина<br>Терешкова','«ВОСТОК-6» / ПЕРВАЯ ЖЕНЩИНА В КОСМОСЕ','Почти трое суток и 48 витков вокруг Земли. Полёт расширил опыт пилотируемой космонавтики и стал важным событием в истории участия женщин в космических программах.','Терешкова выполняла наблюдения, фотографирование и вела бортовые записи. Её полёт проходил одновременно с полётом Валерия Быковского на «Востоке-5».','1963'],['leonov','18.03.1965','Алексей<br>Леонов','«ВОСХОД-2» / ПЕРВЫЙ ВЫХОД В КОСМОС','За пределами корабля человек оказался самостоятельным участником космической работы. Леонов вышел через надувной шлюз и провёл в открытом космосе около 12 минут.','Выход требовал автономного скафандра, страховочного фала и шлюза. Раздувание скафандра затруднило возвращение; это показало, насколько важны испытания оборудования и подготовка к нештатным ситуациям.','1965']];
const tech=[['01','Ракета-носитель','Доставить груз на орбиту','Многоступенчатая ракета набирает необходимую скорость, последовательно сбрасывая отработавшие ступени. Р-7 стала основой носителя первого спутника; для тяжёлых станций применялся «Протон».'],['02','Жизнеобеспечение','Сделать космос обитаемым','Воздух, удаление углекислого газа, вода и тепловой режим — непрерывная работа систем, от которых зависит экипаж. Длительные экспедиции превратили их надёжность в центральную задачу.'],['03','Стыковка','Соединить аппараты в полёте','Сближение требует точного измерения расстояния, скорости и ориентации. Стыковочные узлы позволили менять экипажи, доставлять грузы и наращивать станции.'],['04','Скафандр','Сохранить жизнь вне корабля','Скафандр поддерживает давление, обеспечивает кислород и защиту от тепловых нагрузок. Работа Леонова стала первым практическим опытом выхода человека в открытый космос.'],['05','Связь и автоматика','Работать далеко от Земли','Межпланетные аппараты выполняют последовательности команд и передают измерения по радиоканалу. Задержка сигнала и ограниченная мощность требуют автономного управления.'],['06','Теплозащита','Пережить возвращение','При входе в атмосферу энергия движения превращается в тепло. Защитный экран спасает спускаемый аппарат; для Венеры дополнительно нужны прочный корпус и тепловая изоляция.']];

const viewer=(kind,label)=>`<aside class="narrative-visual"><div class="scene-backdrop"></div><div class="museum-host" data-scene="${kind}" aria-label="${label}"></div>${kind==='mars'?'<span class="signal-status">РЕКОНСТРУКЦИЯ</span>':''}<div class="scene-meta"><span class="scene-epoch"></span><span class="scene-caption">${label}</span><span class="scene-step" aria-hidden="true"></span></div></aside>`;
const story=(id,year,title,text,extra='',stage=0)=>`<article class="narrative-step chapter" id="${id}" data-stage="${stage}" data-year="${year}"><div class="eyebrow">${year}</div><h2>${title}</h2><p class="lead">${text}</p>${extra}</article>`;
const missionStories=(name,data)=>data.map((m,i)=>story(`${name}-mission-${i}`,m[2],m[1],m[3],ref(name==='moon'?'luna':'venera'),i+1)).join('');
document.querySelector('#exhibition').innerHTML=`
<section id="sputnik" class="narrative narrative-sputnik">${viewer('sputnik','Спутник-1 · техническая реконструкция')}<div class="narrative-copy">
${story('sputnik-intro','01 / 04 ОКТЯБРЯ 1957','Сигнал,<br>услышанный<br>всем миром<span class="red">.</span>','«Спутник-1» стал первым искусственным спутником Земли. Небольшая металлическая сфера доказала: созданный человеком аппарат способен выйти на орбиту.',`<div class="metric"><div><b>83,6<span> КГ</span></b><span>МАССА АППАРАТА</span></div><div><b>58<span> СМ</span></b><span>ДИАМЕТР КОРПУСА</span></div><div><b>≈98<span> МИН</span></b><span>ПЕРВЫЙ ВИТОК</span></div></div>${detail('Запуск открыл космическую эру и усилил научное и технологическое соперничество СССР и США. Радиосигналы позволяли следить за спутником с Земли. За простотой аппарата стояли сложные задачи ракетной техники, управления и связи.')}${ref('sputnik')}`)}
${story('sputnik-body','01 / КОРПУС','Всё начинается<br>со сферы.','Сфера защищала приборы и поддерживала внутренние условия работы.',ref('sputnik'),1)}
${story('sputnik-antennas','02 / АНТЕННЫ И СВЯЗЬ','Четыре антенны.<br>Один новый мир.','Длинные стержневые антенны обеспечивали передачу радиосигнала на Землю.',`<p class="lead">Радиоимпульсы позволяли обнаружить спутник и отслеживать его полёт. Это была телеметрия, а не голосовая связь.</p>${ref('sputnik')}`,2)}
</div></section>
<section id="human" class="narrative narrative-human">${viewer('human','«Восток-1» · техническая реконструкция')}<div class="narrative-copy">${humanData.map((p,i)=>story(p[0],p[1],p[2],p[4],`<div class="craft">${p[3]}</div>${detail(p[5])}${ref(p[0])}`,i)).join('')}</div></section>
<section id="moon" class="narrative narrative-moon">${viewer('moon','Луна · карта поверхности / реконструкции аппаратов')}<div class="narrative-copy">
${story('moon-intro','03 / 1959 — 1970','Сначала<br>туда пришли<br>автоматы.','Советские аппараты достигли Луны, показали её обратную сторону, выполнили мягкую посадку и вернули грунт.',`<p class="notice">СССР не высаживал людей на Луну. Пилотируемая лунная программа и успешные автоматические миссии — разные направления.</p>${ref('luna')} · ${ref('soil','Лунный грунт')}`)}
${missionStories('moon',moonMissions)}
</div></section>
<section id="venus" class="narrative narrative-venus">${viewer('venus','Венера · облачная оболочка / «Венера-9»')}<div class="narrative-copy">
${story('venus-intro','04 / 1970 — 1982','Другой мир.<br>Предельные<br>условия.','Под облаками Венеры — раскалённая поверхность и огромное давление. Советские станции серии «Венера» передали оттуда измерения и первые изображения.',`<div class="planet-facts"><div><strong>≈467 °C</strong><span>НА ПОВЕРХНОСТИ</span></div><div><strong>≈93 ×</strong><span>ДАВЛЕНИЕ ЗЕМЛИ</span></div></div>${ref('venusfacts','Условия на планете')} · ${ref('chronicle','Даты посадок')}`)}
${missionStories('venus',venusMissions)}<p class="sequence-end">${ref('venera')} · <a class="source-ref" href="${sources.find(s=>s[0]==='venusphoto')[3]}" target="_blank" rel="noopener">Настоящий снимок «Венеры-13» ↗</a></p>
</div></section>
<section id="mars" class="narrative narrative-mars">${viewer('mars','Марс · карта поверхности / реконструкция «Марса-3»')}<div class="narrative-copy">
${story('mars-intro','04.1 / 02 ДЕКАБРЯ 1971','«Марс-3»:<br>посадка и тишина.','Первая мягкая посадка на Марс состоялась, но передача сигнала прекратилась примерно через 20 секунд. Полноценной панорамы получить не удалось. Это одновременно достижение посадочной техники и пример ограниченного научного результата.',ref('mars'))}
${story('mars-descent','01 / СПУСК','Через атмосферу<br>к поверхности.','Посадочный аппарат отделяется и спускается к поверхности Марса.',`<p class="notice">Анимация — условная реконструкция спуска, не запись полёта. Длительность движения художественно сокращена.</p>${ref('mars')}`,1)}
${story('mars-landing','02 / МЯГКАЯ ПОСАДКА','Аппарат<br>достиг поверхности.','Первая мягкая посадка на Марс состоялась.',ref('mars'),2)}
${story('mars-silence','03 / ПРЕКРАЩЕНИЕ ПЕРЕДАЧИ','Около 20 секунд.<br>Затем тишина.','Передача сигнала прекратилась примерно через 20 секунд. Полноценной панорамы получить не удалось.',`<p class="notice">Венера и Марс исследовались автоматическими аппаратами. Люди на них не высаживались.</p>${ref('mars')}`,3)}
</div></section>
<section id="stations" class="narrative narrative-stations">${viewer('stations','«Салют-1» → «Мир» · реконструкция советского этапа')}<div class="narrative-copy">
${story('salyut-1','05 / 19 АПРЕЛЯ 1971','Не просто<br>полететь.<br>Остаться.','19 апреля 1971 года на орбиту вышел «Салют-1» — первая космическая станция. Программа «Салют» стала школой длительной работы человека за пределами Земли.',`${detail('У «Салюта-6» и «Салюта-7» было по два стыковочных узла: станцию могли посещать транспортные и грузовые корабли. Базовый блок «Мира» запущен 20 февраля 1986 года по московскому времени (19 февраля UTC). Станция работала и после распада СССР; её эксплуатация завершилась в 2001 году.')}${ref('salyut')}`)}
${story('mir-base','1986 / БАЗОВЫЙ БЛОК','«Мир».<br>Начало системы.','В 1986 году началась сборка «Мира»: к базовому блоку добавлялись научные модули. Орбита превращалась в место постоянной исследовательской работы.',`<p class="lead">Жилые помещения, управление и стыковочный узел для будущих модулей.</p>${ref('mir','Станция «Мир»')}`,1)}
${story('mir-kvant','1987 / «КВАНТ»','Первая научная<br>пристройка.','В 1987 году к станции присоединился первый специализированный научный модуль.',ref('mir'),2)}
${story('mir-growth','1989–1990 / «КВАНТ-2» И «КРИСТАЛЛ»','Станция<br>растёт.','В 1989 и 1990 годах добавлены новые модули. Научная программа и возможности работы вне станции расширились.',`<p class="notice">Показан советский этап до 1991 года. Модули «Спектр» и «Природа» добавлены уже после СССР и здесь не показаны.</p>${ref('mir')} · ${ref('hardware','Устройство станции')}`,3)}
<div class="station-hold"><p class="caption">1986 — 1990 / СОВЕТСКИЙ ЭТАП</p><p>Базовый блок, «Квант», «Квант-2» и «Кристалл». Осмотрите собранную станцию, прежде чем продолжить путь.</p></div>
</div></section>
<section class="chapter chapter-body technology" id="technology">${eyebrow('06','ИНЖЕНЕРИЯ ЗА РЕКОРДАМИ')}<h2>Что сделало<br>невозможное возможным?</h2><p class="lead">За каждым «впервые» стояла система решений. Каждая технология решала свою задачу.</p><div class="technology-reading">${tech.map(t=>`<article><span class="caption">${t[0]} / ${t[1].toUpperCase()}</span><h3>${t[2]}</h3><p>${t[3]}</p></article>`).join('')}</div>${ref('hardware','Техническая история аппаратов')} · ${ref('chronicle','Автоматические станции')}</section>
<section class="chapter chapter-body problems" id="problems">${eyebrow('07','ОБРАТНАЯ СТОРОНА ПРОГРЕССА')}<h2>Космос не прощает<br>простых решений.</h2><p class="lead">История достижений неполна без истории риска. Аварии, ограниченные ресурсы и сложность испытаний заставляли пересматривать технику и организацию полётов.</p><div class="problem-list"><div class="problem-item"><span class="mono">1967 / СОЮЗ-1</span><h3>Надёжность —<br>условие полёта</h3><p>24 апреля погиб Владимир Комаров: при спуске отказала парашютная система. Полёт показал тяжесть последствий технических отказов.${ref('komarov')}</p></div><div class="problem-item"><span class="mono">1969–1972 / Н-1</span><h3>Не каждый проект<br>достигает цели</h3><p>Все четыре испытательных запуска ракеты Н-1 завершились неудачами. Советская программа пилотируемой высадки на Луну не была осуществлена.${ref('n1')}</p></div><div class="problem-item"><span class="mono">1971 / СОЮЗ-11</span><h3>Безопасность<br>возвращения</h3><p>Георгий Добровольский, Владислав Волков и Виктор Пацаев погибли из-за разгерметизации при возвращении. После трагедии требования к защите экипажа были пересмотрены.${ref('salyut')}</p></div></div>${detail('Космическая программа требовала дорогой инфраструктуры, большого числа испытаний и координации конструкторских коллективов. Политическое соперничество усиливало давление сроков. Успех отдельных миссий не отменяет человеческих потерь, затрат и технических ограничений; неудачные миссии нельзя считать успешными только потому, что они были первыми.')}</section>
<section class="chapter chapter-body" id="timeline">${eyebrow('08','МАРШРУТ ЭКСПОЗИЦИИ')}<h2>От сигнала —<br>к системе.</h2><p class="lead">События развивались параллельно: пилотируемые полёты, исследования планет и орбитальные станции дополняли друг друга.</p><div class="timeline-list">${[['1957','Первый спутник','sputnik'],['1959','«Луна-2» и «Луна-3»','moon'],['1961','Полёт Гагарина','gagarin'],['1963','Полёт Терешковой','tereshkova'],['1965','Выход Леонова','leonov'],['1966','Мягкая посадка «Луны-9»','moon'],['1970','Грунт Луны и «Луноход-1»','moon'],['1970','Посадка «Венеры-7»','venus'],['1971','«Салют-1»','stations'],['1971','Посадка «Марса-3»','mars'],['1975','Снимки «Венеры-9»','venus'],['1986','Базовый блок «Мира»','stations']].map(t=>`<a href="#${t[2]}"><b>${t[0]}</b><span>${t[1]} ↗</span></a>`).join('')}</div></section>
<section class="chapter chapter-body finale" id="legacy">${eyebrow('09','ИТОГИ И НАСЛЕДИЕ')}<h2>Земля осталась той же.<br>Наши возможности — нет.</h2><p class="lead">Советская космическая программа сыграла ключевую роль в начале космической эры: от первого спутника и полёта человека до автоматического исследования планет и длительной жизни на орбите.</p><p class="lead">Её наследие — не только рекорды, но и инженерный опыт, научные данные и уроки безопасности. Стыковка «Союза» и «Аполлона» в 1975 году показала ещё одну возможность: сотрудничество.</p>${ref('astp','«Союз — Аполлон»')}<div class="legacy-orbits" aria-hidden="true"><div class="legacy-earth"></div>${[1,2,3,4,5].map(i=>`<i style="--n:${i}"></i>`).join('')}</div><p class="caption">ОТ ОДНОГО СПУТНИКА — К МНОЖЕСТВУ НАПРАВЛЕНИЙ ИССЛЕДОВАНИЯ</p></section>
<section class="chapter chapter-body sources" id="sources">${eyebrow('10','ПРОВЕРЯЕМЫЕ ФАКТЫ')}<h2>Источники и материалы</h2><p class="lead">Ссылки ведут к историческим обзорам, каталогам миссий и техническим публикациям. Основные даты на сайте — даты событий, а не всегда даты запуска аппаратов.</p><div class="sources-grid">${sources.map((s,i)=>`<a id="source-${s[0]}" href="${s[3]}" target="_blank" rel="noopener">${String(i+1).padStart(2,'0')} / ${s[1]} ↗<span>${s[2]}</span></a>`).join('')}</div><div class="credits"><p>Границы проекта: СССР, 1957–1991. Более поздняя работа «Мира» упоминается только как продолжение программы. Авторы проекта: Балыков, Хайсаров, Попеску, Войнич. По рекомендациям преподавателя А. П. Грибачевой.</p><p>Аппараты — авторские технические 3D-реконструкции. Масштабы сцен, движение и длительность анимаций условны. Карты Земли — NASA Blue Marble; Луна, Марс и облачная Венера — Solar System Scope (CC BY 4.0). Рельеф и освещение художественно усилены. Шрифт Manrope хранится локально (SIL OFL). <a class="source-ref" href="assets/ATTRIBUTION.md" target="_blank" rel="noopener">Источники графики и лицензии ↗</a></p><p>Советские достижения рассматриваются в историческом контексте; символические приоритеты не подменяют оценку научного результата и человеческого риска.</p></div></section>`;
const chapters=[...document.querySelectorAll('.chapter')],progress=document.querySelector('#progress');let current=0,presenting=false,queued=false;
function updateScroll(){queued=false;const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${max>0?scrollY/max*100:0}%`;current=0;chapters.forEach((c,i)=>{let focus=innerHeight*.55;const visual=c.closest('.narrative')?.querySelector('.narrative-visual');if(innerWidth<761&&visual){const readingTop=Math.min(innerHeight-80,parseFloat(getComputedStyle(visual).top)+visual.getBoundingClientRect().height);focus=readingTop+(innerHeight-readingTop)*.45}if(c.getBoundingClientRect().top<=focus)current=i});document.querySelector('#slide-label').textContent=`${current+1} / ${chapters.length}`;document.querySelector('#prev').disabled=current===0;document.querySelector('#next').disabled=current===chapters.length-1;document.querySelectorAll('nav a').forEach(a=>{let id=chapters[current].id;if(['gagarin','tereshkova','leonov'].includes(id))id='human';if(id.startsWith('moon-'))id='moon';if(id.startsWith('venus-')||id.startsWith('mars-'))id='venus';if(id.startsWith('sputnik-'))id='sputnik';if(id.startsWith('mir-')||id==='salyut-1')id='stations';a.classList.toggle('active',a.hash==='#'+id)})}
addEventListener('scroll',()=>{if(!queued){queued=true;requestAnimationFrame(updateScroll)}},{passive:true});addEventListener('resize',updateScroll);updateScroll();function setPresent(on){presenting=on;document.body.classList.toggle('presenting',on);document.querySelector('#presentation-bar').hidden=!on;document.querySelector('#present').setAttribute('aria-pressed',String(on));if(on)document.querySelector('#next').focus();else document.querySelector('#present').focus();updateScroll()}
document.querySelector('#present').addEventListener('click',()=>setPresent(!presenting));document.querySelector('#exit').addEventListener('click',()=>setPresent(false));function step(n){current=Math.max(0,Math.min(chapters.length-1,current+n));chapters[current].scrollIntoView({behavior:'instant',block:'start'});updateScroll()}document.querySelector('#prev').addEventListener('click',()=>step(-1));document.querySelector('#next').addEventListener('click',()=>step(1));addEventListener('keydown',e=>{if(e.key==='Escape'&&presenting)setPresent(false);if(presenting&&!e.target.matches('canvas,input,select,summary,[role=tab],[data-scene],.webgl-view')&&['ArrowRight','ArrowLeft','PageDown','PageUp'].includes(e.key)){e.preventDefault();step(['ArrowRight','PageDown'].includes(e.key)?1:-1)}});

document.querySelector("#mobile-nav").addEventListener("change",e=>{location.hash=e.target.value});
