import * as T from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {sputnik,vostok,luna9,venera9,mesh} from './models.js';

const motion=matchMedia('(prefers-reduced-motion: reduce)');
const mobile=()=>innerWidth<761;
const clamp=T.MathUtils.clamp;
const asset=name=>window.__MUSEUM_ASSETS__?.[name]||new URL(`assets/${name}`,document.baseURI).href;
const orbitPoint=(phase)=>new T.Vector3(3.3*Math.cos(phase),.95*Math.sin(phase),3.15*Math.sin(phase));
const viewSpecs=[
 {id:'earth',host:'.earth-stage',kind:'earth',label:'Земля и Спутник-1. Перетаскивайте для изменения ракурса',distance:8.8},
 {id:'sputnik-model',host:'#sputnik .scene',kind:'sputnik',label:'3D-модель Спутника-1',distance:5.2},
 {id:'vostok-model',host:'.journey-display',kind:'vostok',label:'3D-модель корабля Восток и схема выхода Леонова',distance:6.7},
 {id:'luna-model',host:'.moon-visual',kind:'luna',label:'3D-модель раскрытой капсулы Луны-9',distance:4.6},
 {id:'venera-model',host:'#venus .planet',kind:'venera',label:'3D-модель посадочного аппарата Венеры-9',distance:5.4}
];
let renderer,env,views=[],raf=0,last=0,clock=0,dirty=true,paused=false,quality=1,slowFrames=0,frames=0,totalMs=0;
let completedOrbits=0;
let orbitPhase=2.35,sceneSun=new T.Vector3(-6,2.2,3).normalize(),qaPanel=null,contextLost=false,disposed=false;
const sphereGeometry=new T.SphereGeometry(2,96,64),temp=new T.Vector3(),raycaster=new T.Raycaster();

function mountViews(){
 document.querySelector('#earth').remove();
 for(const spec of viewSpecs){
  const host=document.querySelector(spec.host);if(!host)continue;host.classList.add("model-mounted");
  if(spec.kind==='venera'){host.className='venera-visual model-mounted';host.removeAttribute('role');host.removeAttribute('aria-label')}
  const view=document.createElement('div');view.className=`webgl-view view-${spec.kind}`;view.id=spec.id;view.tabIndex=0;view.setAttribute('role','group');view.setAttribute('aria-label',spec.label+'. Мышь или касание — вращение; стрелки — поворот; плюс и минус — масштаб.');
  view.innerHTML=`<span class="view-status">Подготовка экспоната…</span><div class="view-corner top-left"></div><div class="view-corner bottom-right"></div>`;
  host.prepend(view);
  const tools=document.createElement('div');tools.className='viewer-tools';tools.innerHTML=`<span class="drag-label">↔ ТЯНУТЬ</span><button type="button" data-action="out" aria-label="Отдалить: ${spec.label}">−</button><button type="button" data-action="in" aria-label="Приблизить: ${spec.label}">+</button><button type="button" data-action="reset" aria-label="Вернуть ракурс: ${spec.label}">↺</button>`;view.append(tools);
  const readout=document.createElement('div');readout.className='model-readout';readout.setAttribute('aria-live','polite');if(spec.kind!=='earth'){readout.innerHTML='<span class="model-kicker">ИНТЕРАКТИВНЫЙ ЭКСПОНАТ</span><strong>Исследуйте устройство</strong><p>Поверните модель или выберите отмеченную деталь.</p>';host.append(readout)}
  const v={...spec,el:view,host,tools,readout,ready:false,building:false,active:false,scene:null,camera:null,model:null,hotspots:[],yaw:spec.kind==='earth'?0:.48,pitch:spec.kind==='earth'?.08:.16,vy:0,vp:0,zoom:1,targetZoom:1,drag:false,lastInput:-99,parallax:new T.Vector2(),targetParallax:new T.Vector2(),pointer:null,rect:null};views.push(v);bindControls(v);
 }
 document.querySelector('.earth-hint').innerHTML='↔ ВРАЩАЙТЕ СЦЕНУ <span>NASA BLUE MARBLE / 3D</span>';
 document.querySelector('.orbital-label').innerHTML='ПС-1 / СПУТНИК<br><span>04 ОКТЯБРЯ 1957</span><br><span class="orbit-readout">ОРБИТАЛЬНЫЙ ПОЛЁТ</span>';
 const captions=[['#sputnik .caption','СПУТНИК-1 · ТЕХНИЧЕСКАЯ 3D-РЕКОНСТРУКЦИЯ'],['#moon .caption','«ЛУНА-9» · ПОСАДОЧНАЯ КАПСУЛА · РЕКОНСТРУКЦИЯ']];
 for(const [sel,text] of captions){const el=document.querySelector(sel);if(el)el.textContent=text}
 const venusCaption=[...document.querySelectorAll('#venus .caption')].find(e=>e.textContent.includes('ХУДОЖЕСТВЕННАЯ'));if(venusCaption)venusCaption.textContent='«ВЕНЕРА-9» · ПОСАДОЧНЫЙ АППАРАТ · РЕКОНСТРУКЦИЯ';
 const credits=[...document.querySelectorAll('.credits p')].find(e=>e.textContent.includes('Все иллюстрации'));if(credits)credits.innerHTML='3D-аппараты — авторские технические реконструкции по музейным и научным материалам; детали и масштаб сцены условны. Поверхность Земли и облака — карты NASA Blue Marble, а не погода 1957 года. Иллюстрации не являются фотографиями исторических полётов. <a href="assets/ATTRIBUTION.md" target="_blank" rel="noopener">Источники графики и лицензии ↗</a>';
}
function bindControls(v){
 v.el.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;v.pointer={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,type:e.pointerType,t:performance.now()};v.drag=true;v.vy=v.vp=0;v.lastInput=clock;v.el.setPointerCapture(e.pointerId);v.el.classList.add('dragging');wake()});
 v.el.addEventListener('pointermove',e=>{const r=v.el.getBoundingClientRect();if(v.drag&&v.pointer){const now=performance.now(),dt=Math.max(.008,(now-v.pointer.t)/1000),dx=e.clientX-v.pointer.x,dy=e.clientY-v.pointer.y;v.yaw-=dx*.005;v.pitch=clamp(v.pitch+(e.pointerType==='touch'?0:dy*.004),-.95,.95);v.vy=clamp(-dx*.005/dt,-1.3,1.3);v.vp=clamp((e.pointerType==='touch'?0:dy*.004)/dt,-.8,.8);v.pointer.x=e.clientX;v.pointer.y=e.clientY;v.pointer.t=now;v.lastInput=clock;wake()}else if(!mobile()&&!motion.matches){v.targetParallax.set((e.clientX-r.left)/r.width-.5,(e.clientY-r.top)/r.height-.5);pick(v,e,false);wake()}});
 const up=e=>{if(v.pointer&&Math.hypot(e.clientX-v.pointer.startX,e.clientY-v.pointer.startY)<6)pick(v,e,true);v.drag=false;v.pointer=null;v.lastInput=clock;v.el.classList.remove('dragging');wake()};v.el.addEventListener('pointerup',up);v.el.addEventListener('pointercancel',()=>{v.drag=false;v.pointer=null;v.vy=v.vp=0;v.el.classList.remove('dragging');wake()});v.el.addEventListener('pointerleave',()=>{v.targetParallax.set(0,0);wake()});
 v.el.addEventListener('keydown',e=>{const keys=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-'];if(!keys.includes(e.key))return;e.preventDefault();e.stopPropagation();if(e.key==='ArrowLeft')v.yaw-=.13;if(e.key==='ArrowRight')v.yaw+=.13;if(e.key==='ArrowUp')v.pitch=clamp(v.pitch+.1,-.95,.95);if(e.key==='ArrowDown')v.pitch=clamp(v.pitch-.1,-.95,.95);if(e.key==='+'||e.key==='=')v.targetZoom=clamp(v.targetZoom*.9,.72,1.4);if(e.key==='-')v.targetZoom=clamp(v.targetZoom*1.1,.72,1.4);v.lastInput=clock;wake()});
 v.tools.addEventListener('click',e=>{const action=e.target.closest('button')?.dataset.action;if(!action)return;if(action==='reset'){v.yaw=v.kind==='earth'?0:.48;v.pitch=.1;v.vp=v.vy=0;v.targetZoom=1}else v.targetZoom=clamp(v.targetZoom*(action==='in'?.88:1.12),.72,1.4);v.lastInput=clock;wake()});
}
function selectHotspot(v,h){v.readout.innerHTML=`<span class="model-kicker">ДЕТАЛЬ ЭКСПОНАТА</span><strong>${h.title}</strong><p>${h.text}</p>`;v.hotspots.forEach(x=>{x.dot.scale.setScalar(.034*(x===h?1.35:1));x.button?.setAttribute('aria-pressed',String(x===h))});wake()}
function pick(v,event,click){if(!v.ready||v.kind==='earth')return;const r=v.el.getBoundingClientRect(),p=new T.Vector2((event.clientX-r.left)/r.width*2-1,-(event.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(p,v.camera);const hits=raycaster.intersectObject(v.model,true);const first=hits.find(x=>x.object.isMesh);const h=v.hotspots.find(h=>h.dot===first?.object);v.el.classList.toggle('over-hotspot',!!h);if(h&&(click||!v.drag))selectHotspot(v,h)}
function lighting(scene,warm=false){scene.add(new T.HemisphereLight(warm?0xffdec0:0xcbddeb,0x0c111c,.4));const sun=new T.DirectionalLight(warm?0xffdbac:0xfff2de,3.2);sun.position.set(-4,5,5);scene.add(sun);const fill=new T.DirectionalLight(warm?0xb29782:0x8db7da,.55);fill.position.set(4,1,-3);scene.add(fill);scene.environment=env;return sun}
function starfield(scene){let seed=17;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};for(let layer=0;layer<3;layer++){const n=(mobile()?90:170)/(layer+1)|0,positions=[],colors=[];for(let i=0;i<n;i++){positions.push((rnd()-.5)*50,(rnd()-.5)*32,-12-rnd()*22-layer*15);let b=.25+rnd()*.5;colors.push(b*.82,b*.92,b)}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(positions,3));geo.setAttribute('color',new T.Float32BufferAttribute(colors,3));const points=new T.Points(geo,new T.PointsMaterial({size:.028+layer*.017,vertexColors:true,transparent:true,opacity:.6,sizeAttenuation:true,depthWrite:false}));scene.add(points)}}
async function texture(name,color=false){const t=await new T.TextureLoader().loadAsync(asset(name));t.colorSpace=color?T.SRGBColorSpace:T.NoColorSpace;t.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy());return t}
function roughnessMap(image){const c=document.createElement('canvas');c.width=512;c.height=256;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,512,256);const data=ctx.getImageData(0,0,512,256);for(let i=0;i<data.data.length;i+=4){const [r,g,b]=data.data.slice(i,i+3);const ocean=b>r*1.3&&b>g*1.04;const val=ocean?110:232;data.data[i]=data.data[i+1]=data.data[i+2]=val;data.data[i+3]=255}ctx.putImageData(data,0,0);return new T.CanvasTexture(c)}
async function buildEarth(v){const scene=v.scene;starfield(scene);const globe=new T.Group();globe.rotation.z=.12;scene.add(globe);const earth=mesh(sphereGeometry,new T.MeshStandardMaterial({color:0xffffff,roughness:1,metalness:0,envMap:env,envMapIntensity:.025}),globe);earth.castShadow=true;earth.receiveShadow=false;earth.rotation.y=3.9;v.earth=earth;v.globe=globe;
 const sun=new T.DirectionalLight(0xfff3df,2.7);sun.position.copy(sceneSun).multiplyScalar(12);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-4.5;sun.shadow.camera.right=4.5;sun.shadow.camera.top=4.5;sun.shadow.camera.bottom=-4.5;sun.shadow.camera.near=1;sun.shadow.camera.far=25;sun.shadow.bias=-.0005;sun.shadow.normalBias=.012;scene.add(sun);scene.add(new T.AmbientLight(0x8aabcf,.04));scene.environment=env;
 const cloudMat=new T.MeshStandardMaterial({color:0xfff9ed,transparent:true,opacity:.87,depthTest:true,depthWrite:false,roughness:1,envMap:env,envMapIntensity:.015,side:T.FrontSide});const clouds=mesh(new T.SphereGeometry(2.009,96,64),cloudMat,globe);clouds.castShadow=false;clouds.receiveShadow=false;clouds.rotation.y=earth.rotation.y;v.clouds=clouds;
 const atm=new T.Mesh(new T.SphereGeometry(2.034,80,48),new T.ShaderMaterial({transparent:true,side:T.BackSide,depthTest:true,depthWrite:false,uniforms:{sun:{value:sceneSun}},vertexShader:`varying vec3 n; varying vec3 p; void main(){vec4 w=modelMatrix*vec4(position,1.);p=w.xyz;n=normalize(mat3(modelMatrix)*normal);gl_Position=projectionMatrix*viewMatrix*w;}`,fragmentShader:`uniform vec3 sun; varying vec3 n; varying vec3 p; void main(){vec3 v=normalize(cameraPosition-p);float rim=pow(1.-abs(dot(normalize(n),v)),3.0);float day=smoothstep(-.28,.55,dot(normalize(n),sun));gl_FragColor=vec4(.20,.46,.78,rim*(.07+.42*day));}`}));globe.add(atm);v.atmosphere=atm;
 const model=sputnik();model.hotspots.forEach(h=>h.anchor.removeFromParent());model.root.scale.setScalar(.27);v.satellite=model.root;v.satellite.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.envMap=env;o.material.envMapIntensity=.22;o.receiveShadow=true}});scene.add(model.root);
 const points=[];for(let i=0;i<=240;i++)points.push(orbitPoint(i/240*Math.PI*2));v.orbit=new T.LineLoop(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color:0x80919f,transparent:true,opacity:.33,depthTest:true,depthWrite:false}));scene.add(v.orbit);
 const [day,cloudTex]=await Promise.all([texture('earth-day.jpg',true),texture('earth-clouds.jpg')]);earth.material.map=day;earth.material.roughnessMap=roughnessMap(day.image);earth.material.needsUpdate=true;cloudMat.alphaMap=cloudTex;cloudMat.needsUpdate=true;v.model=globe;
}
async function buildView(v){if(v.building||v.ready||disposed)return;v.building=true;v.scene=new T.Scene();v.camera=new T.PerspectiveCamera(v.kind==='earth'?38:37,1,.05,100);try{if(v.kind==='earth'){await buildEarth(v)}else{lighting(v.scene,v.kind==='venera');const object=({sputnik,vostok,luna:luna9,venera:venera9})[v.kind]();v.model=object.root;v.parts=object;v.hotspots=object.hotspots;v.scene.add(v.model);if(v.kind==='sputnik'){v.model.position.y=.8;v.model.rotation.z=-.62}if(v.kind==='luna')v.model.rotation.y=-.3;if(v.kind==='venera')v.model.position.y=-.2;
  const labels=document.createElement('div');labels.className='model-parts';labels.setAttribute('aria-label','Детали 3D-модели');v.hotspots.forEach((h,i)=>{const b=document.createElement('button');b.type='button';b.textContent=String(i+1).padStart(2,'0')+' '+h.title;b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>selectHotspot(v,h));h.button=b;labels.append(b)});v.host.append(labels);selectHotspot(v,v.hotspots[0]);
 }v.ready=true;v.host.classList.add('has-model');v.el.querySelector('.view-status').textContent=v.kind==='earth'?'ЗЕМЛЯ / NASA BLUE MARBLE':'3D / ВРАЩАЙТЕ · ИССЛЕДУЙТЕ';v.el.dataset.ready='true';wake()}catch(e){v.el.querySelector('.view-status').textContent='Не удалось загрузить 3D — описание доступно ниже';v.el.dataset.ready='error';console.error('Model load:',v.kind,e)}}
function onResize(){if(!renderer)return;renderer.setPixelRatio(Math.min(devicePixelRatio||1,mobile()?1.25:1.65)*quality);renderer.setSize(innerWidth,innerHeight,false);dirty=true;wake()}
function wake(){dirty=true;if(!raf&&!document.hidden&&!contextLost&&!disposed)raf=requestAnimationFrame(tick)}
function updateView(v,dt){if(!v.drag&&!motion.matches){v.yaw+=v.vy*dt;v.pitch=clamp(v.pitch+v.vp*dt,-.95,.95);const damp=Math.exp(-5*dt);v.vy*=damp;v.vp*=damp}if(motion.matches){v.vy=v.vp=0;v.parallax.set(0,0);v.zoom=v.targetZoom}else{v.parallax.lerp(v.targetParallax,1-Math.exp(-3*dt));v.zoom=T.MathUtils.damp(v.zoom,v.targetZoom,6,dt)}
 const r=v.rect;let travel=0;if(!motion.matches){if(v.kind==='earth')travel=clamp(-r.top/innerHeight,0,1)*.8;else if(v.kind==='vostok'){const section=document.querySelector('#human').getBoundingClientRect();const fraction=clamp((100-section.top)/(section.height-innerHeight),0,1);v.model.rotation.y=T.MathUtils.damp(v.model.rotation.y,fraction*.65,3,dt);v.model.rotation.z=T.MathUtils.damp(v.model.rotation.z,-.1+fraction*.12,3,dt)}else if(v.kind==='luna'||v.kind==='venera'){const progress=clamp((innerHeight-r.top)/(innerHeight+r.height),0,1);v.model.rotation.y=T.MathUtils.damp(v.model.rotation.y,(progress-.5)*.32,3,dt)}}
 const distance=v.distance*v.zoom+travel,angle=v.yaw+(motion.matches?0:v.parallax.x*.055),pitch=v.pitch+(motion.matches?0:v.parallax.y*.025);v.camera.position.set(Math.sin(angle)*Math.cos(pitch)*distance,Math.sin(pitch)*distance,Math.cos(angle)*Math.cos(pitch)*distance);v.camera.lookAt(0,0,0);v.camera.aspect=r.width/r.height;v.camera.updateProjectionMatrix();
 if(v.kind==='earth'){v.satellite.position.copy(orbitPoint(orbitPhase));v.satellite.rotation.y=clock*.045;v.satellite.rotation.z=-.6;v.orbit.rotation.set(0,0,0);if(!paused&&!motion.matches&&!v.drag&&clock-v.lastInput>3){v.earth.rotation.y+=dt*.007;v.clouds.rotation.y+=dt*.0081}v.el.dataset.phase=String(Math.round(orbitPhase*180/Math.PI)%360);const label=document.querySelector('.orbit-readout');if(label)label.textContent='ФАЗА '+String(Math.round((orbitPhase%(Math.PI*2))/(Math.PI*2)*360)).padStart(3,'0')+'° · МАСШТАБ УСЛОВНЫЙ';}
 if(v.kind==='vostok'){const leonov=document.querySelector('#scene-year').textContent==='1965';v.parts.eva.visible=leonov;v.model.scale.setScalar(leonov?.78:1);v.el.dataset.epoch=document.querySelector('#scene-year').textContent;v.el.querySelector('.view-status').textContent=leonov?'«ВОСХОД-2» / СХЕМА ВЫХОДА':`«ВОСТОК-${document.querySelector('#scene-year').textContent==='1963'?'6':'1'}» / ТЕХНИЧЕСКАЯ МОДЕЛЬ`;}
 v.scene.updateMatrixWorld(true);
}
function tick(now){raf=0;if(document.hidden||contextLost||disposed)return;const dt=Math.min(.05,last?(now-last)/1000:1/60);last=now;clock+=dt;const live=views.filter(v=>v.active&&v.ready);if(!paused&&!motion.matches){const next=orbitPhase+dt*.17;if(next>=Math.PI*2)completedOrbits++;orbitPhase=next%(Math.PI*2)}
 const start=performance.now();renderer.setScissorTest(false);renderer.setClearColor(0,0);renderer.clear(true,true,true);renderer.setScissorTest(true);let activeCount=0,calls=0,triangles=0;
 for(const v of live){const r=v.el.getBoundingClientRect();v.rect=r;if(r.bottom<0||r.top>innerHeight||r.width<1||r.height<1)continue;updateView(v,dt);renderer.setViewport(r.left,innerHeight-r.bottom,r.width,r.height);const left=Math.max(0,r.left),bottom=Math.max(0,innerHeight-r.bottom),right=Math.min(innerWidth,r.right),top=Math.min(innerHeight,innerHeight-r.top);renderer.setScissor(left,bottom,Math.max(0,right-left),Math.max(0,top-bottom));renderer.clear(true,true,true);renderer.render(v.scene,v.camera);calls+=renderer.info.render.calls;triangles+=renderer.info.render.triangles;activeCount++}
 renderer.setScissorTest(false);frames++;totalMs+=performance.now()-start;if(activeCount&&dt>.036&&!vDragging()){slowFrames++;if(slowFrames>120&&quality>.65){quality=Math.max(.65,quality-.15);slowFrames=0;onResize()}}else slowFrames=Math.max(0,slowFrames-1);
 if(qaPanel&&frames%20===0){qaPanel.querySelector('output').textContent=JSON.stringify({contexts:1,activeViews:activeCount,dpr:renderer.getPixelRatio(),calls,triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,frames,meanCpuMs:+(totalMs/frames).toFixed(2),phase:Math.round(orbitPhase*180/Math.PI),completedOrbits,yaw:+views[0].yaw.toFixed(3),inertia:+views[0].vy.toFixed(3),reducedMotion:motion.matches,contextLost},null,2)}
 dirty=false;const inertia=live.some(v=>Math.abs(v.vy)+Math.abs(v.vp)>.002||Math.abs(v.zoom-v.targetZoom)>.001);if((live.length&&!paused&&!motion.matches)||inertia)raf=requestAnimationFrame(tick)
}
function vDragging(){return views.some(v=>v.drag)}

// QA renders the actual Earth and satellite into a private target. Visibility is
// never changed by orbital phase in the live scene: the GPU depth buffer decides.
async function depthAudit(){const v=views.find(v=>v.kind==='earth');if(!v.ready)return;const saved={phase:orbitPhase,yaw:v.yaw,pitch:v.pitch,zoom:v.zoom,paused,earth:v.earth.material,cloud:v.clouds.visible,atmosphere:v.atmosphere.visible,orbit:v.orbit.visible};const target=new T.WebGLRenderTarget(256,256,{depthBuffer:true,stencilBuffer:false});const pixels=new Uint8Array(256*256*4),materials=[];const white=new T.MeshBasicMaterial({color:0xffffff,depthTest:true,depthWrite:true}),red=new T.MeshBasicMaterial({color:0xff0000,depthTest:true,depthWrite:true});v.satellite.traverse(o=>{if(o.isMesh){materials.push([o,o.material]);o.material=red}});v.earth.material=white;v.clouds.visible=false;v.atmosphere.visible=false;v.orbit.visible=false;paused=true;const result=[];try{renderer.setScissorTest(false);renderer.setRenderTarget(target);for(const yaw of [0,.55,-.65]){v.yaw=yaw;v.pitch=.08;v.zoom=1;for(const phase of [0,Math.PI/2,Math.PI,Math.PI*1.5]){orbitPhase=phase;v.rect={left:0,top:0,bottom:256,width:256,height:256};updateView(v,0);let counts=[];for(const earthVisible of [false,true]){v.earth.visible=earthVisible;renderer.setClearColor(0x000000,1);renderer.clear();renderer.render(v.scene,v.camera);renderer.readRenderTargetPixels(target,0,0,256,256,pixels);let count=0;for(let i=0;i<pixels.length;i+=4)if(pixels[i]>120&&pixels[i+1]<50&&pixels[i+2]<50)count++;counts.push(count)}result.push({yaw,phase:Math.round(phase*180/Math.PI),withoutEarth:counts[0],withEarth:counts[1],occluded:counts[0]>0&&counts[1]===0})}}}finally{v.earth.visible=true;v.earth.material=saved.earth;v.clouds.visible=saved.cloud;v.atmosphere.visible=saved.atmosphere;v.orbit.visible=saved.orbit;materials.forEach(([o,m])=>o.material=m);orbitPhase=saved.phase;v.yaw=saved.yaw;v.pitch=saved.pitch;v.zoom=saved.zoom;paused=saved.paused;renderer.setRenderTarget(null);target.dispose();white.dispose();red.dispose();wake()}
 const hidden=result.filter(r=>r.occluded).length;qaPanel.querySelector('.audit-result').textContent=JSON.stringify({passed:hidden>=3&&result.some(r=>r.withEarth>0),hiddenCases:hidden,results:result},null,2);return result}
function mountQA(){if(!new URLSearchParams(location.search).has('qa'))return;qaPanel=document.createElement('details');qaPanel.className='graphics-qa';qaPanel.open=true;qaPanel.innerHTML='<summary>Проверка 3D</summary><label>Фаза орбиты <input aria-label="Фаза орбиты" type="range" min="0" max="360" value="135"></label><button class="pause">Пауза орбиты</button><button class="depth-audit">Проверить глубину</button><label>Ракурс <select aria-label="Тестовый ракурс"><option value="0">Фронтальный</option><option value="0.55">Справа</option><option value="-0.65">Слева</option></select></label><output></output><pre class="audit-result"></pre>';document.body.append(qaPanel);qaPanel.querySelector('input').addEventListener('input',e=>{paused=true;orbitPhase=Number(e.target.value)*Math.PI/180;wake()});qaPanel.querySelector('.pause').addEventListener('click',e=>{paused=!paused;e.target.textContent=paused?'Продолжить орбиту':'Пауза орбиты';wake()});qaPanel.querySelector('select').addEventListener('change',e=>{views[0].yaw=Number(e.target.value);views[0].vy=0;wake()});qaPanel.querySelector('.depth-audit').addEventListener('click',depthAudit)}
export async function initMuseum(){mountViews();try{renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});}catch(error){document.documentElement.classList.add('webgl-unavailable');document.querySelectorAll('.view-status').forEach(e=>e.textContent='WebGL недоступен — доступна схема');return}
 renderer.domElement.className='webgl-layer';renderer.domElement.setAttribute('aria-hidden','true');renderer.autoClear=false;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;document.body.append(renderer.domElement);const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment();env=pmrem.fromScene(room,.02).texture;room.dispose();pmrem.dispose();onResize();
 const observer=new IntersectionObserver(entries=>{for(const entry of entries){const v=views.find(v=>v.el===entry.target);v.active=entry.isIntersecting;if(entry.isIntersecting)buildView(v)}wake()},{rootMargin:'80px'});views.forEach(v=>observer.observe(v.el));
 addEventListener('scroll',wake,{passive:true});addEventListener('resize',onResize);motion.addEventListener('change',wake);document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;last=0}else wake()});renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;cancelAnimationFrame(raf);raf=0;document.documentElement.classList.add('webgl-unavailable');views.forEach(v=>v.el.querySelector('.view-status').textContent='3D приостановлено — схема и текст доступны')});renderer.domElement.addEventListener('webglcontextrestored',()=>{contextLost=false;document.documentElement.classList.remove('webgl-unavailable');onResize();wake()});
 addEventListener('pagehide',e=>{if(e.persisted)return;disposed=true;cancelAnimationFrame(raf);observer.disconnect();const geos=new Set(),materials=new Set(),textures=new Set();views.forEach(v=>v.scene?.traverse(o=>{if(o.geometry)geos.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])if(m){materials.add(m);Object.values(m).forEach(t=>{if(t?.isTexture)textures.add(t)})}}));geos.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());env.dispose();renderer.dispose()});mountQA();wake();
}
